# hb/triggers.yml - 触发条件配置

triggers:
  # 定时触发
  schedule:
    - name: "daily_check"
      description: "每天检查一次"
      cron: "0 17 * * *"  # UTC 17:00 = 北京时间 01:00
      task: "merge_nodes"
      
  # 文件变化触发
  file_change:
    - name: "nodes_update"
      description: "nodes目录文件变化"
      watch_path: "../nodes"
      patterns: ["*.txt", "*.yaml", "*.yml"]
      task: "merge_nodes"
      debounce: 300        # 防抖时间（秒）
      
  # 手动触发
  manual:
    - name: "force_process"
      description: "手动强制处理"
      task: "merge_nodes"
      
  # Webhook触发
  webhook:
    - name: "api_trigger"
      description: "API接口触发"
      endpoint: "/api/trigger"
      task: "merge_nodes"
      
  # 组合触发
  composite:
    - name: "full_process"
      description: "完整处理流程"
      conditions:
        - "schedule.daily_check"
        - "manual.force_process"
      tasks:
        - "merge_nodes"
        - "split_by_protocol"
        - "validate_nodes"
        - "backup_results"
